name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
        run:
            shell: ${{ matrix.shell }}

    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest]
        os: [ubuntu-latest, windows-latest]
        #os: [windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            arch: 'win64_msvc2019_64'
            host: 'windows'
            shell: 'powershell'
            #shell: 'cmd'
            #shell: 'msys2 {0}'
          - os: ubuntu-latest
            arch: 'gcc_64'
            host: 'linux'
            shell: 'bash'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install ninja-build tool (must be after Qt due PATH changes)
      uses: turtlesec-no/get-ninja@main

    - name: Make sure MSVC is found when Ninja generator is in use
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y build-essential
    
    - name: Configure
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}/lib/cmake
      run: cmake -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ./build

    - name: Build
      run: cmake --build ./build

    #- name: Unittests on Linux
      #if: matrix.os == 'ubuntu-latest'
      #env:
        #QT_QPA_PLATFORM: offscreen
        #DISPLAY: :1
      #run: |
        #./build/alp_external/radix/unittests/unittests_radix
        #./build/unittests/nucleus/unittests_nucleus
        #Xvfb :1 -screen 0 1024x768x16 &
        #sleep 5
        #./build/unittests/gl_engine/unittests_gl_engine

    #- name: Unittests on Windows
      #if: matrix.os == 'windows-latest'
      #env:
        #MESA_GL_VERSION_OVERRIDE: 3.3
      #run: |
        #./build/alp_external/radix/unittests/unittests_radix.exe
        #./build/unittests/unittests_nucleus.exe
        #./build/unittests/unittests_gl_engine.exe
        
